<?php
/**
 * Created by PhpStorm.
 * User: alexxorlovv
 * Date: 29.09.17
 * Time: 15:17
 */

use PHPUnit\Framework\TestCase;
use Sweetkit\Foundation\Log\{Logger,Log};

class LogTest extends TestCase
{
    protected $log;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testLog()
    {

    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
